### PR TITLE
Improve handling of tagscreate script execution

### PR DESCRIPTION
**Pull request by b0o**
Fixes:
- incorrect string concatenation caused the wrong script name to be used when job_start not supported

Enhancements:
- add support for jobstart (neovim)
- improve output messages

### CODE REVIEW

**Comment by ntnn** [comment]
LGTM, I'll test this later this weekend and merge. Thanks.

**Comment by ntnn** [comment]
I haven't used neovim - is the job control there also documented on `|job|`? If not please update the help file accordingly for vim and neovim.

**Comment by b0o** [comment]
@ntnn Thanks for the feedback! I updated the docs and replaced a comment I accidentally removed.

**Comment by ntnn** [comment]
Sorry that this took so long, I wasn't able to have a closer look at it before going on vacation.

Thanks for the PR, merged.

**Pull request merged**
